In [14]:
import numpy as np
%matplotlib notebook

ModuleNotFoundError: No module named 'matplotlib'

#### Ones 2x3

In [4]:
matrixOnlyOnes = np.ones((2,3))
matrixOnlyOnes

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Zeros 2x3

In [5]:
matrixOnlyZeros = np.zeros((2,3))
matrixOnlyZeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### Matrix Identity 3x3

In [6]:
matrixIdentity = np.eye(3)
matrixIdentity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random Normal Dist. Matrix 2x3

In [8]:
matrixRandNormalDistribution = np.random.normal(size = (2,3))
matrixRandNormalDistribution

array([[-0.17900891,  1.19508368,  1.8776102 ],
       [-0.27235387, -2.29046348,  0.78491817]])

#### Random Uniform Matrix 2x3

In [9]:
matrixRand = np.random.uniform(size = (2,3))
matrixRand

array([[0.01551268, 0.92432089, 0.8860577 ],
       [0.69528511, 0.35890169, 0.02980333]])

In [10]:
np.histogram(matrixRandNormalDistribution)

(array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1]),
 array([-2.29046348, -1.87365611, -1.45684874, -1.04004137, -0.62323401,
        -0.20642664,  0.21038073,  0.6271881 ,  1.04399547,  1.46080284,
         1.8776102 ]))